import { useMemo, useState } from "react";
import CodeMirror from "@uiw/react-codemirror";
import { StreamLanguage } from "@codemirror/language";
import { stex } from "@codemirror/legacy-modes/mode/stex";
import { latexLight } from "../lib/editorTheme";
import type { Extension } from "@codemirror/state";
import { inlineSuggestions, type SuggestionCallbacks } from "../lib/inlineSuggest";
import { buildFileTree, isImageFile, type FileNode } from "../lib/fileTree";
import type { ProposedEdit } from "../lib/api";

const latex = StreamLanguage.define(stex);

interface Props {
  value: string;
  onChange: (value: string) => void;
  onCursor?: (pos: { line: number; col: number }) => void;
  /** OPEN buffers, shown as tabs. */
  files: string[];
  /** All editable project files, shown in the tree (superset of `files`). */
  projectFiles?: string[];
  active: string;
  onSelect: (file: string) => void;
  /** Close an open tab (never called for main.tex — it is pinned). */
  onCloseTab?: (file: string) => void;
  /** Server-side session files not in `files` — e.g. figures from run_python. */
  generatedFiles?: string[];
  /** URL serving a session file's content, for previews of generated files. */
  fileUrl?: (name: string) => string;
  /** Pending agent edits to render inline (Cursor-style accept/reject). */
  suggestions?: ProposedEdit[];
  onAcceptSuggestion?: (edit: ProposedEdit) => void;
  onRejectSuggestion?: (edit: ProposedEdit) => void;
}

function FileIcon({ active }: { active?: boolean }) {
  return (
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke={active ? "#a89a6b" : "#b0a99f"} strokeWidth="1.3">
      <path d="M3 1.5h5l3 3v8H3z" />
      {active && <path d="M8 1.5v3h3" />}
    </svg>
  );
}

function FolderIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="#b0a99f" strokeWidth="1.3">
      <path d="M1.5 3h4l1.5 2h5.5v6.5h-11z" />
    </svg>
  );
}

function TreeLevel({
  nodes,
  active,
  preview,
  onPick,
}: {
  nodes: FileNode[];
  active: string;
  preview: string | null;
  onPick: (node: FileNode) => void;
}) {
  return (
    <ul className="filetree-level">
      {nodes.map((node) =>
        node.children ? (
          <li key={node.path}>
            <div className="filetree-row filetree-dir">
              <FolderIcon />
              {node.name}
            </div>
            <TreeLevel nodes={node.children} active={active} preview={preview} onPick={onPick} />
          </li>
        ) : (
          <li key={node.path}>
            <div
              className={`filetree-row${
                node.path === (preview ?? active) ? " filetree-active" : ""
              }`}
              onClick={() => onPick(node)}
            >
              <FileIcon active={node.path === (preview ?? active)} />
              <span className="filetree-name">{node.name}</span>
              {node.generated && <span className="filetree-gen" title="Generated by the agent" />}
            </div>
          </li>
        ),
      )}
    </ul>
  );
}

export default function EditorPane({
  value,
  onChange,
  onCursor,
  files,
  projectFiles,
  active,
  onSelect,
  onCloseTab,
  generatedFiles,
  fileUrl,
  suggestions,
  onAcceptSuggestion,
  onRejectSuggestion,
}: Props) {
  const [showTree, setShowTree] = useState(true);
  // A generated (server-side) file being previewed instead of the editor.
  // `stamp` busts the browser cache so a regenerated figure re-renders.
  const [preview, setPreview] = useState<{ path: string; stamp: number } | null>(null);

  const tree = useMemo(
    () => buildFileTree(projectFiles ?? files, generatedFiles ?? []),
    [projectFiles, files, generatedFiles],
  );
  // A previewed file can disappear (e.g. new browser session dir) — fall back.
  const previewGone = preview && !(generatedFiles ?? []).includes(preview.path);
  const activePreview = preview && !previewGone ? preview : null;

  const pick = (node: FileNode) => {
    if (node.generated) {
      setPreview({ path: node.path, stamp: Date.now() });
    } else {
      setPreview(null);
      onSelect(node.path);
    }
  };
  // .tex files get LaTeX highlighting; other buffers (e.g. .bib) render plain.
  // The inline-suggestion extension is rebuilt whenever the pending set changes.
  const extensions = useMemo(() => {
    const exts: Extension[] = active.endsWith(".tex") ? [latex] : [];
    if (suggestions && suggestions.length > 0 && onAcceptSuggestion && onRejectSuggestion) {
      const cb: SuggestionCallbacks = {
        onAccept: onAcceptSuggestion,
        onReject: onRejectSuggestion,
      };
      exts.push(inlineSuggestions(suggestions, cb));
    }
    return exts;
  }, [active, suggestions, onAcceptSuggestion, onRejectSuggestion]);

  return (
    <div className="pane editor-pane">
      <div className="tabstrip">
        <button
          className={`tree-toggle${showTree ? " tree-toggle-on" : ""}`}
          onClick={() => setShowTree((s) => !s)}
          title={showTree ? "Hide files" : "Show files"}
        >
          <svg width="13" height="13" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.3">
            <path d="M1.5 3h4l1.5 2h5.5v6.5h-11z" />
          </svg>
        </button>
        {files.map((f) => {
          const isActive = f === active && !activePreview;
          return (
            <div
              key={f}
              className={`tab${isActive ? " tab-active" : " tab-muted"}`}
              onClick={() => {
                setPreview(null);
                onSelect(f);
              }}
            >
              <FileIcon active={isActive} />
              {f}
              {f !== "main.tex" && onCloseTab && (
                <span
                  className="tab-close"
                  title="Close"
                  onClick={(e) => {
                    e.stopPropagation();
                    onCloseTab(f);
                  }}
                >
                  ×
                </span>
              )}
            </div>
          );
        })}
        {activePreview && (
          <div className="tab tab-active tab-preview">
            <FileIcon active />
            {activePreview.path}
            <span className="tab-close" title="Close preview" onClick={() => setPreview(null)}>
              ×
            </span>
          </div>
        )}
      </div>
      <div className="editor-main">
        {showTree && (
          <div className="filetree">
            <TreeLevel
              nodes={tree}
              active={active}
              preview={activePreview?.path ?? null}
              onPick={pick}
            />
          </div>
        )}
        {activePreview && fileUrl ? (
          <div className="pane-body file-preview">
            {isImageFile(activePreview.path) ? (
              <img
                src={`${fileUrl(activePreview.path)}&v=${activePreview.stamp}`}
                alt={activePreview.path}
              />
            ) : (
              <iframe
                title={activePreview.path}
                src={`${fileUrl(activePreview.path)}&v=${activePreview.stamp}`}
              />
            )}
          </div>
        ) : (
          <div className="pane-body editor-body">
            <CodeMirror
              key={active}
              value={value}
              height="100%"
              theme={latexLight}
              extensions={extensions}
              onChange={onChange}
              onUpdate={(vu) => {
                if (!onCursor) return;
                if (vu.selectionSet || vu.docChanged) {
                  const head = vu.state.selection.main.head;
                  const line = vu.state.doc.lineAt(head);
                  onCursor({ line: line.number, col: head - line.from + 1 });
                }
              }}
              basicSetup={{
                lineNumbers: true,
                highlightActiveLine: true,
                bracketMatching: true,
                closeBrackets: true,
              }}
            />
          </div>
        )}
      </div>
    </div>
  );
}
