import { spawn } from "node:child_process";
import { mkdir, writeFile, readFile, readdir, stat, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const TMP_ROOT = path.resolve(__dirname, "..", "tmp");

// Prefer the locally-downloaded Tectonic, fall back to PATH.
const LOCAL_TECTONIC = path.join(REPO_ROOT, "bin", "tectonic");
const TECTONIC_BIN = process.env.TECTONIC_BIN ?? LOCAL_TECTONIC;

// Generous: the first-ever compile downloads LaTeX packages over the network.
const COMPILE_TIMEOUT_MS = Number(process.env.COMPILE_TIMEOUT_MS ?? 300_000);

// Session dirs older than this are deleted at startup.
const SESSION_MAX_AGE_MS = 24 * 60 * 60 * 1000;

export interface CompileResult {
  ok: boolean;
  /** PDF bytes when ok; undefined otherwise. */
  pdf?: Buffer;
  /** Combined stdout+stderr from Tectonic (the build log). */
  log: string;
}

/** A sessionId is used as the working-directory name; sanitize to avoid traversal. */
function safeSessionDir(sessionId: string): string {
  const clean = sessionId.replace(/[^a-zA-Z0-9_-]/g, "").slice(0, 64) || "default";
  return path.join(TMP_ROOT, clean);
}

/**
 * The working directory Tectonic compiles in for a given session. Other tools
 * (e.g. run_python generating figures) write here so `\includegraphics{fig}`
 * resolves against the same directory the compiler runs in.
 */
export function sessionDir(sessionId: string): string {
  return safeSessionDir(sessionId);
}

/**
 * Validate a project-relative file path (e.g. "refs.bib", "sections/intro.tex").
 * Rejects absolute paths, traversal, and unusual characters. Returns the
 * normalized relative path, or undefined if it is not safe to write.
 */
function safeRelPath(name: string): string | undefined {
  if (!/^[a-zA-Z0-9._/-]{1,128}$/.test(name)) return undefined;
  const norm = path.posix.normalize(name);
  if (norm.startsWith("/") || norm.startsWith("..") || norm.includes("/../")) return undefined;
  return norm;
}

/**
 * Write auxiliary project files (bibliographies, \input'd sections, …) into a
 * session's compile directory so Tectonic can resolve them. Unsafe paths are
 * skipped. `main.tex` is skipped too — compileTex owns it.
 */
export async function writeSessionFiles(
  sessionId: string,
  files: Record<string, string>,
): Promise<void> {
  const dir = safeSessionDir(sessionId);
  for (const [name, content] of Object.entries(files)) {
    const rel = safeRelPath(name);
    if (!rel || rel === "main.tex") continue;
    const target = path.join(dir, rel);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
  }
}

/** Build artifacts, view_pdf previews, and underscore-prefixed scratch files
 * (run_python's _agent_script.py, mermaid's _diagram.mmd/_puppeteer.json) —
 * not project files. */
const NON_PROJECT_FILE = /^main\.(tex|pdf|log|aux|out|toc|bbl|blg)$|^preview-\d+\.png$|^_/;

/**
 * Project files present in a session's compile dir (aux files from earlier
 * requests, figures generated by run_python) — so the agent can be told what
 * \includegraphics/\input can already resolve. Build artifacts are excluded.
 */
export async function listSessionFiles(sessionId: string): Promise<string[]> {
  const dir = safeSessionDir(sessionId);
  let names: string[];
  try {
    names = (await readdir(dir, { recursive: true })) as string[];
  } catch {
    return []; // dir doesn't exist yet
  }
  const files: string[] = [];
  for (const name of names) {
    const rel = name.split(path.sep).join("/");
    if (NON_PROJECT_FILE.test(rel)) continue;
    try {
      if ((await stat(path.join(dir, name))).isFile()) files.push(rel);
    } catch {
      /* deleted between readdir and stat */
    }
  }
  return files.sort();
}

/** File types a user may upload into the session (data files, images, bibs). */
const UPLOAD_EXT = /\.(csv|tsv|xlsx|xls|json|txt|dat|png|jpe?g|svg|pdf|bib)$/i;

/**
 * Write one user-uploaded file (binary-safe) into a session's compile dir so
 * run_python can read it (pandas) and \includegraphics/\input can resolve it.
 * Returns the normalized relative path, or undefined when the name is unsafe,
 * the extension is not allowed, or it would clobber main.tex.
 */
export async function writeSessionUpload(
  sessionId: string,
  name: string,
  data: Buffer,
): Promise<string | undefined> {
  const rel = safeRelPath(name);
  if (!rel || rel === "main.tex" || !UPLOAD_EXT.test(rel) || NON_PROJECT_FILE.test(rel)) {
    return undefined;
  }
  const target = path.join(safeSessionDir(sessionId), rel);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, data);
  return rel;
}

/**
 * Absolute path of a project file inside a session dir, for serving it to the
 * client (file-tree preview). Undefined when the name is unsafe (traversal)
 * or not a project file (build artifacts, run_python's scratch script).
 */
export function sessionFilePath(sessionId: string, name: string): string | undefined {
  const rel = safeRelPath(name);
  if (!rel || NON_PROJECT_FILE.test(rel)) return undefined;
  return path.join(safeSessionDir(sessionId), rel);
}

/** Delete session dirs that have not been touched in SESSION_MAX_AGE_MS. */
export async function cleanupStaleSessions(): Promise<void> {
  let names: string[];
  try {
    names = await readdir(TMP_ROOT);
  } catch {
    return; // no tmp dir yet
  }
  const cutoff = Date.now() - SESSION_MAX_AGE_MS;
  for (const name of names) {
    const dir = path.join(TMP_ROOT, name);
    try {
      const st = await stat(dir);
      if (st.isDirectory() && st.mtimeMs < cutoff) {
        await rm(dir, { recursive: true, force: true });
      }
    } catch {
      /* ignore races and permission issues */
    }
  }
}

/**
 * Detect a native engine crash (as opposed to a normal LaTeX error) and return
 * an actionable hint. The most common cause on this setup is the fontawesome5
 * package: at load time it introspects glyph names via \XeTeXglyphname, which
 * aborts Tectonic's XeTeX engine (`free(): invalid pointer`). The classic v4
 * `fontawesome` package does not do this and compiles fine.
 */
function diagnoseCrash(
  log: string,
  code: number | null,
  signal: NodeJS.Signals | null,
  tex: string,
): string | undefined {
  const crashMarkers =
    /free\(\): invalid pointer|double free|corrupted|segmentation fault|core dumped|SIGABRT|SIGSEGV/i;
  const crashed = code === null || signal !== null || crashMarkers.test(log);
  if (!crashed) return undefined;

  const base = `The LaTeX engine (Tectonic) CRASHED${
    signal ? ` with signal ${signal}` : ""
  } — this is an engine abort, not a normal LaTeX error, so re-running the same source will crash again.`;

  if (/fontawesome/i.test(log) || /fontawesome/i.test(tex) || /\.otf\b/i.test(log)) {
    return (
      base +
      " Cause: the fontawesome5 package crashes this system's XeTeX engine (it probes glyph names via \\XeTeXglyphname at load time). Fix: replace \\usepackage{fontawesome5} with \\usepackage{fontawesome} — the classic v4 package compiles fine here and keeps the same \\faXxx icon commands (\\faEnvelope, \\faPhone, \\faGithub, \\faLinkedin, \\faMapMarker, …)."
    );
  }
  return (
    base +
    " It is usually triggered by loading OTF fonts via fontspec/fontawesome on this system. Try removing custom OTF font packages and using standard LaTeX fonts."
  );
}

/**
 * Pull the detailed error blocks out of a TeX .log file. Tectonic's console
 * output only says e.g. "error: main.tex:5: Undefined control sequence" — the
 * .log has the part that makes the error fixable: which token failed and the
 * offending source line ("<recently read> \badmacro", "l.5 \badmacro").
 * Returns each "!" error line plus its context lines, blocks joined by blank
 * lines; empty string when the log has no error blocks.
 */
export function extractTexLogErrors(texLog: string, maxChars = 2000): string {
  const lines = texLog.split(/\r?\n/);
  const blocks: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (!lines[i].startsWith("!")) continue;
    const block: string[] = [lines[i]];
    // Context runs until the blank line after the "l.<num>" source line (TeX
    // prints the offending line split in two), the next error, or a hard cap.
    let sawSourceLine = false;
    let j = i + 1;
    for (; j < lines.length && block.length < 12; j++) {
      const line = lines[j];
      if (line.startsWith("!")) break;
      if (sawSourceLine && line.trim() === "") break;
      block.push(line);
      if (/^l\.\d+/.test(line)) sawSourceLine = true;
    }
    blocks.push(block.join("\n").trimEnd());
    i = j - 1;
  }
  const out = blocks.join("\n\n");
  return out.length <= maxChars ? out : out.slice(0, maxChars) + "\n… (more errors omitted)";
}

/**
 * Line numbers of errors in main.tex, from the console output
 * ("error: main.tex:5: …") and the .log's "l.5 …" context lines. Bare "l.N"
 * numbers refer to whatever file TeX was reading at the time, so they are only
 * trusted when no console error names a different file.
 */
export function errorLineNumbers(consoleLog: string, logDetails: string): number[] {
  const nums = new Set<number>();
  let sawOtherFile = false;
  for (const m of consoleLog.matchAll(/^error: ([^\s:]+):(\d+):/gm)) {
    if (/(^|\/)main\.tex$/.test(m[1])) nums.add(Number(m[2]));
    else sawOtherFile = true;
  }
  if (!sawOtherFile) {
    for (const m of logDetails.matchAll(/^l\.(\d+)/gm)) nums.add(Number(m[1]));
  }
  return [...nums].sort((a, b) => a - b);
}

/**
 * Quote the source around the reported error lines, numbered, with the error
 * lines marked. Models cannot reliably COUNT lines in the document to find
 * "main.tex:5" — this hands them the exact text to anchor an edit on.
 */
export function sourceAtLines(
  tex: string,
  lineNums: number[],
  context = 2,
  maxLines = 40,
): string {
  const lines = tex.split(/\r?\n/);
  const include = new Set<number>();
  for (const n of lineNums) {
    const from = Math.max(1, n - context);
    const to = Math.min(lines.length, n + context);
    for (let i = from; i <= to; i++) include.add(i);
  }
  const ordered = [...include].sort((a, b) => a - b).slice(0, maxLines);
  const out: string[] = [];
  let prev = 0;
  for (const n of ordered) {
    if (prev && n > prev + 1) out.push("  …");
    out.push(`${lineNums.includes(n) ? ">" : " "} ${n}: ${lines[n - 1]}`);
    prev = n;
  }
  return out.join("\n");
}

/** Environments whose body TeX reads verbatim — \begin/\end tokens inside them
 * are literal text, except the env's own \end. */
const VERBATIM_ENVS = new Set(["verbatim", "verbatim*", "Verbatim", "lstlisting", "minted"]);

export interface EnvironmentIssue {
  /** e.g. "\begin{frame} opened at line 63 is never closed …" */
  description: string;
  /** Line in main.tex to quote: the unclosed \begin, or the stray \end. */
  line: number;
}

/**
 * Balance-check \begin/\end pairs in the source. Needed because "File ended
 * while scanning use of …" errors carry NO line number at all — TeX only
 * notices the problem at end of file, long after the unclosed \begin. Stack
 * matching attributes the leftover open environment to the right line even
 * when later same-name pairs are balanced (each \end closes the innermost
 * open env, so the one missing its \end is the one left on the stack).
 * Comments and verbatim bodies are skipped.
 */
export function findEnvironmentIssues(tex: string): EnvironmentIssue[] {
  const issues: EnvironmentIssue[] = [];
  const stack: { env: string; line: number }[] = [];
  let verbatim: string | undefined;
  const lines = tex.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const lineNo = i + 1;
    // Cut the line at the first unescaped % — the rest is a comment.
    const code = lines[i].match(/^(?:\\.|[^\\%])*/)?.[0] ?? lines[i];
    for (const m of code.matchAll(/\\(begin|end)\s*\{([^}]*)\}/g)) {
      const [, kind, env] = m;
      if (verbatim) {
        if (!(kind === "end" && env === verbatim)) continue; // literal text
        verbatim = undefined; // fall through: this \end still pops the stack
      }
      if (kind === "begin") {
        if (VERBATIM_ENVS.has(env)) verbatim = env;
        stack.push({ env, line: lineNo });
        continue;
      }
      if (stack.length && stack[stack.length - 1].env === env) {
        stack.pop();
        continue;
      }
      // \end doesn't match the innermost open env: either envs opened after
      // its \begin were never closed, or it is a stray \end.
      let matchAt = -1;
      for (let k = stack.length - 1; k >= 0; k--) {
        if (stack[k].env === env) {
          matchAt = k;
          break;
        }
      }
      if (matchAt === -1) {
        issues.push({
          description: `\\end{${env}} at line ${lineNo} has no matching \\begin{${env}}`,
          line: lineNo,
        });
        continue;
      }
      for (let k = stack.length - 1; k > matchAt; k--) {
        issues.push({
          description:
            `\\begin{${stack[k].env}} opened at line ${stack[k].line} is never closed — ` +
            `it is still open when \\end{${env}} at line ${lineNo} is reached. ` +
            `Add the missing \\end{${stack[k].env}}`,
          line: stack[k].line,
        });
      }
      stack.length = matchAt;
    }
  }
  for (const open of stack) {
    issues.push({
      description:
        `\\begin{${open.env}} opened at line ${open.line} is never closed ` +
        `(the file ends while it is still open). Add the missing \\end{${open.env}}`,
      line: open.line,
    });
  }
  return issues;
}

/**
 * Locate the cause of no-line-number failures ("File ended while scanning use
 * of \beamer@collect@@body", "Runaway argument?"). Their console output is
 * actively misleading: the only line numbers in it belong to "Missing
 * character … nullfont" warnings, which are downstream symptoms. Scan the
 * source ourselves and quote the unclosed \begin so the model fixes the cause.
 */
export function diagnoseUnbalanced(
  consoleLog: string,
  details: string,
  tex: string,
): string | undefined {
  const combined = consoleLog + "\n" + details;
  if (!/File ended while scanning|Runaway argument|\\end occurred inside a group/i.test(combined)) {
    return undefined;
  }
  const parts: string[] = [
    'This "File ended while scanning"-type error carries NO line number because TeX only ' +
      "noticed the problem at the end of the file: something opened earlier is never closed, " +
      "so the real defect is EARLIER in the document.",
  ];
  if (/beamer@collect@@body/.test(combined)) {
    parts.push(
      "\\beamer@collect@@body means beamer was still collecting a frame body: " +
        "a \\begin{frame} is missing its \\end{frame}.",
    );
  }
  if (/nullfont/.test(consoleLog)) {
    parts.push(
      'The "Missing character … nullfont" warnings are a downstream symptom of the same ' +
        "problem, not separate errors — do NOT edit the lines they mention.",
    );
  }
  const issues = findEnvironmentIssues(tex).slice(0, 5);
  if (issues.length === 0) {
    parts.push(
      "An environment balance scan found every \\begin/\\end matched, so the culprit is an " +
        "unclosed brace group: look for a { without its } (often in a command argument).",
    );
    return parts.join(" ");
  }
  return (
    parts.join(" ") +
    `\n\nEnvironment scan of main.tex found:\n` +
    issues.map((i) => `- ${i.description}`).join("\n") +
    `\n\nmain.tex source at the unclosed \\begin line(s) — anchor your fix on this EXACT text. ` +
    `The "> N:"/"  N:" prefixes are line-number annotations, NOT part of the file:\n` +
    sourceAtLines(
      tex,
      issues.map((i) => i.line),
    )
  );
}

/**
 * Per-session compile queue. Two Tectonic processes must never run in the same
 * directory at once (they share main.tex/main.pdf), so compiles for a given
 * session are chained; different sessions still compile in parallel.
 */
const sessionQueues = new Map<string, Promise<unknown>>();

function enqueue<T>(key: string, job: () => Promise<T>): Promise<T> {
  const prev = sessionQueues.get(key) ?? Promise.resolve();
  const next = prev.then(job, job);
  sessionQueues.set(key, next);
  // Drop the queue entry once idle so the map doesn't grow forever.
  next.finally(() => {
    if (sessionQueues.get(key) === next) sessionQueues.delete(key);
  });
  return next;
}

export async function compileTex(sessionId: string, tex: string): Promise<CompileResult> {
  const dir = safeSessionDir(sessionId);
  return enqueue(dir, () => compileTexNow(dir, tex));
}

async function compileTexNow(dir: string, tex: string): Promise<CompileResult> {
  await mkdir(dir, { recursive: true });
  const mainPath = path.join(dir, "main.tex");
  await writeFile(mainPath, tex, "utf8");
  // Drop any previous run's log so a crash that dies before writing a new one
  // can't make us report stale errors below.
  const logPath = path.join(dir, "main.log");
  await rm(logPath, { force: true });

  const args = [
    "-X",
    "compile",
    "--outdir",
    dir,
    "--keep-logs",
    "main.tex",
  ];

  return new Promise<CompileResult>((resolve) => {
    let log = "";
    let child;
    try {
      child = spawn(TECTONIC_BIN, args, { cwd: dir });
    } catch (err) {
      resolve({ ok: false, log: `Failed to launch Tectonic (${TECTONIC_BIN}): ${String(err)}` });
      return;
    }

    const timer = setTimeout(() => {
      log += `\n[killed: compile exceeded ${Math.round(COMPILE_TIMEOUT_MS / 1000)}s time limit]`;
      child.kill("SIGKILL");
    }, COMPILE_TIMEOUT_MS);

    child.stdout.on("data", (d) => (log += d.toString()));
    child.stderr.on("data", (d) => (log += d.toString()));
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ ok: false, log: `${log}\nTectonic process error: ${String(err)}` });
    });
    child.on("close", async (code, signal) => {
      clearTimeout(timer);
      const hint = diagnoseCrash(log, code, signal, tex);
      const withHint = (body: string) => (hint ? `${hint}\n\n${body}` : body);
      if (code !== 0) {
        // Tectonic's console output names the failing line but not the detail
        // (which macro, what token) — that lives in main.log (--keep-logs).
        let details = "";
        try {
          details = extractTexLogErrors(await readFile(logPath, "utf8"));
        } catch {
          /* engine may have died before writing the log */
        }
        // Quote main.tex at the reported lines: models fix "the wrong line"
        // when they have to count lines in the document themselves.
        const errLines = errorLineNumbers(log, details);
        const source = errLines.length
          ? `\n\nmain.tex source at the reported line(s) — anchor your fix on this EXACT text. ` +
            `The "> N:"/"  N:" prefixes are line-number annotations, NOT part of the file:\n` +
            sourceAtLines(tex, errLines)
          : "";
        // No-line-number failures (unclosed frame/environment) get a source
        // scan instead — the console output for those points at symptom lines.
        const unbalanced = diagnoseUnbalanced(log, details, tex);
        const full =
          (details ? `${log}\n\nError details from main.log:\n${details}` : log) +
          source +
          (unbalanced ? `\n\n${unbalanced}` : "");
        resolve({ ok: false, log: withHint(full || `Tectonic exited with code ${code}`) });
        return;
      }
      try {
        const pdf = await readFile(path.join(dir, "main.pdf"));
        resolve({ ok: true, pdf, log });
      } catch (err) {
        resolve({
          ok: false,
          log: withHint(`${log}\nCompile succeeded but PDF not found: ${String(err)}`),
        });
      }
    });
  });
}
